/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BasicCreater: typeof import('./src/components/BasicCreater.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    ICollapse: typeof import('./src/system/components/ICollapse.vue')['default']
    IDrawer: typeof import('./src/system/components/IDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SystemAccountPasswordUpdater: typeof import('./src/system/components/SystemAccountPasswordUpdater.vue')['default']
    SystemAdminAccountCreater: typeof import('./src/system/components/SystemAdminAccountCreater.vue')['default']
    SystemAdminAccountEditer: typeof import('./src/system/components/SystemAdminAccountEditer.vue')['default']
    SystemAdminMenuCreater: typeof import('./src/system/components/SystemAdminMenuCreater.vue')['default']
    SystemAdminPermissionCreater: typeof import('./src/system/components/SystemAdminPermissionCreater.vue')['default']
    SystemAdminRoleCreater: typeof import('./src/system/components/SystemAdminRoleCreater.vue')['default']
    SystemAdminRoleEditer: typeof import('./src/system/components/SystemAdminRoleEditer.vue')['default']
    SystemDeleter: typeof import('./src/system/components/SystemDeleter.vue')['default']
    SystemMenuLeft: typeof import('./src/system/components/SystemMenuLeft.vue')['default']
    SystemMenuTop: typeof import('./src/system/components/SystemMenuTop.vue')['default']
  }
}
