/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/system/account/profile': RouteRecordInfo<'/system/account/profile', '/system/account/profile', Record<never, never>, Record<never, never>>,
    '/system/admin/account': RouteRecordInfo<'/system/admin/account', '/system/admin/account', Record<never, never>, Record<never, never>>,
    '/system/admin/menu': RouteRecordInfo<'/system/admin/menu', '/system/admin/menu', Record<never, never>, Record<never, never>>,
    '/system/admin/permission': RouteRecordInfo<'/system/admin/permission', '/system/admin/permission', Record<never, never>, Record<never, never>>,
    '/system/admin/role': RouteRecordInfo<'/system/admin/role', '/system/admin/role', Record<never, never>, Record<never, never>>,
    '/system/authenticate/sigin': RouteRecordInfo<'/system/authenticate/sigin', '/system/authenticate/sigin', Record<never, never>, Record<never, never>>,
  }
}
